version: "2"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml
    ports:
      - "8080:8080"
