
NeoBundleLazy 'osyo-manga/vim-jplus', {'autoload':{
\ 'mappings' : [['nv',
\   '<Plug>(jplus-getchar)', '<Plug>(jplus-getchar-with-space)',
\   '<Plug>(jplus-input)', '<Plug>(jplus-input-with-space)',
\ ]]}}

NeoBundleLazy 'Shougo/junkfile.vim', { 'autoload' : {
\ 'commands' : ['JunkfileOpen'],
\ }}
" \ 'unite_sources' : ['junkfile', 'junkfile/new'],

NeoBundleLazy 'Shougo/vinarise', {
\ 'commands' : [
\ {'name' : 'Vinarise',
\  'complete' : 'customlist,vinarise#complete'},
\ {'name' : 'VinariseDump',
\  'complete' : 'customlist,vinarise#complete'},
\ {'name' : 'VinariseScript2Hex',
\  'complete' : 'customlist,vinarise#complete'}],
\ }
" \ 'unite_sources' : 'vinarise/analysis'

NeoBundleLazy 'tyru/capture.vim', {'autoload': {
\ 'commands': [{'name':'Capture', 'complete':'command'}],
\ }}

" NeoBundleLazy 'tpope/vim-abolish', {'autoload': {
" \ 'commands': [
" \ {'name': 'Abolish'}, {'name': 'Subvert'},
" \ ],
" \ 'mappings': [['n', '<Plug>Coerce']]
" \ }}

NeoBundleLazy 't9md/vim-quickhl', {'autoload': {
\ 'commands': [
\ 'QuickhlManualEnable', 'QuickhlManualDisable', 'QuickhlManualList',
\ 'QuickhlManualReset', 'QuickhlManualColors', 'QuickhlManualAdd',
\ 'QuickhlManualDelete', 'QuickhlManualLock', 'QuickhlManualUnlock',
\ 'QuickhlManualLockToggle', 'QuickhlManualLockWindow', 'QuickhlManualUnlockWindow',
\ 'QuickhlManualLockWindowToggle', 'QuickhlCwordEnable', 'QuickhlCwordDisable',
\ 'QuickhlCwordToggle', 'QuickhlTagEnable', 'QuickhlTagDisable',
\ 'QuickhlTagToggle',
\ ],
\ 'function_prefix':'quickhl',
\ 'mappings': [['nv', '<Plug>(quickhl-',
\ '<Plug>(operator-quickhl-manual-this-motion)']],
\ }}

NeoBundleLazy 'bkad/CamelCaseMotion', { 'autoload' : {
\ 'mappings' : ['<Plug>CamelCaseMotion_w',
\ '<Plug>CamelCaseMotion_b'],
\ }}

NeoBundleLazy 'h1mesuke/vim-alignta', {'autoload': {
\ 'commands': [
\ {'name': 'Align'},
\ {'name': 'Alignta'},
\ ],
\ }}
" \ 'unite_sources': ['alignta']

NeoBundleLazy 'AndrewRadev/splitjoin.vim', {'autoload': {
\ 'commands': ['SplitjoinJoin', 'SplitjoinSplit'],
\ }}

NeoBundleLazy 'AndrewRadev/inline_edit.vim', {'autoload': {
\ 'commands': [
\ {'name': 'InlineEdit'},
\ ],
\ }}

NeoBundleLazy 'glidenote/memolist.vim', {'autoload': {
\ 'commands': ['MemoNew', 'MemoGrep', 'MemoList']
\ }}

NeoBundleLazy 'thinca/vim-prettyprint', { 'autoload': {
\ 'commands' : [
\   { 'name' : 'PP', 'complete': 'expression'},
\   { 'name' : 'PrettyPrint', 'complete': 'expression'},
\ ]}}

NeoBundleLazy 'deris/vim-rengbang', {'autoload':{
\ 'commands': ['RengBang'],
\ 'mappings': ['<Plug>(operator-rengbang'],
\ }}

NeoBundleLazy 'rhysd/unite-codic.vim', {'autoload': {
\ 'unite_sources': 'codic',
\ }}


NeoBundleLazy 'mattn/emoji-vim', {'autoload': {
\ 'commands': ['Emoji'],
\ 'mappings': [['in', '<plug>(emoji-selector']],
\ }}

NeoBundleLazy 'vim-scripts/ShowMultiBase', {'autoload':{
\ 'commands': ['ShowMultiBase'],
\ }}
