web:
  image: php:5.4-apache
  ports:
    - "40080:80"
  volumes:
    - ./app_src:/var/www/html
  links:
    - mysql
mysql:
  image: mysql:5.6
  ports:
    - '43306:3306'
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  # password: <%= ENV['DB_ENV_MYSQL_ROOT_PASSWORD'] %>
  # host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>
  # port: <%= ENV['DB_PORT_3306_TCP_PORT'] %>


