web:
  # image: php:5.4-apache
  build: .
  ports:
    - "40080:80"
  volumes:
    - ./app_src:/var/www/html
  links:
    - mysql
mysql:
  image: mysql:5.6
  ports:
    - '43306:3306'
  volumes_from:
    - file
  # volumes:
  #   - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  # password: <%= ENV['MYSQL_ENV_MYSQL_ROOT_PASSWORD'] %>
  # host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  # port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] %>

file:
  build: containers/data/
