version: "2"
services:
  swagger-ui:
    # https://hub.docker.com/r/swaggerapi/swagger-ui/tags
    image: swaggerapi/swagger-ui
    volumes:
      - ./:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml
    ports:
      - "8080:8080"
  swagger-editor:
    # https://hub.docker.com/r/swaggerapi/swagger-editor/tags
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
